spring:
  application:
    name: blogging-platform-api
  datasource:
    url: >-
      jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:blogging-platform}
    username: '${DB_USER:bp}'
    password: '${DB_PASSWORD:bp}'
  jpa:
    properties:
      hibernate:
        dialect: '${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}'
    hibernate:
      ddl-auto: validate
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    property-naming-strategy: SNAKE_CASE
server:
  port: '${PORT:9090}'
